---
provider: virtualbox
box: wyd/ubuntu103 #boxname
version: ">= 1.0.0" #box版本
name: wydUbuntu8 #virtualbox中的虚拟主机名称
hostname: wydUbuntu #虚拟主机hostname
username: ubuntu #虚拟主机登录用户名
ip: "192.168.10.10"
memory: 2048
cpus: 2


#authorize: ~/.ssh/id_rsa.pub
authorize: ../../id_rsa.pub
keys:
#    - ~/.ssh/id_rsa
    - ../../id_rsa

afterSh: after.sh

defaultPhpVersion: php7.0  #默认php版本 包括命令行和php-fpm 通过 /usr/local/bin 中的php phpize 等软连接实现

folders:
    - map: D:\vagrant\data
      to: /data
sites:
    - domain: php70.vg
      phpversion: "7.0"
    - domain: php56.vg
      type: common
      webpath: /data/wwwroot/php56.vg
      logpath: /data/wwwlogs/php56.vg.log
      phpversion: "5.6"
    - domain: php72.vg
      type: common
      webpath: /data/wwwroot/php72.vg
      logpath: /data/wwwlogs/php72.vg.log
      phpversion: "7.2"
#databases:
#    - homestead
# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
